// ---------------------------------------------------------------------
// Background music track list. Add or remove filenames here to change
// which tracks are eligible to be picked by js/music.js. Paths are
// relative to index.html (i.e. inside the audio/ folder at the project
// root).
// ---------------------------------------------------------------------
export const MUSIC_TRACKS = [
    'audio/07-Fluss.mp3',
    'audio/07-decent-sampler-1.mp3',
    'audio/07-decent-sampler2.mp3',
    'audio/07-ruismaker-noir.mp3',
    'audio/08-decent-sampler-1.mp3',
    'audio/08-decent-sampler-2.mp3',
    'audio/08-ruismaker-noir.mp3',
    'audio/11-animoog-1.mp3',
    'audio/11-animoog-2.mp3',
    'audio/11-decent-sampler.mp3',
    'audio/11-soundbox.mp3',
    'audio/11-synthmaster.mp3',
    'audio/12-decent-sampler.mp3',
    'audio/12-ruismaker-noir.mp3',
    'audio/12-synthmaster-1.mp3',
    'audio/12-synthmaster-2.mp3',
    'audio/13-decent-sampler-2.mp3',
    'audio/13-decentsampler-1.mp3',
    'audio/13-fluss-1.mp3',
    'audio/13-fluss-2.mp3',
    'audio/13-ruismaker-noir.mp3',
    'audio/13-synthmaster.mp3',
    'audio/15-dm10.mp3',
    'audio/15-j6-synth.mp3',
    'audio/16-decent-sampler.mp3',
    'audio/16-dm10.mp3',
    'audio/16-j6-synth.mp3',
    'audio/16-synthmaster.mp3',
    'audio/18-battlestation.mp3',
    'audio/18-decent-sampler.mp3',
    'audio/18-dm10.mp3',
    'audio/18-j6-synth.mp3',
    'audio/20-battlestation.mp3',
    'audio/20-decent-sampler.mp3',
    'audio/20-j6-synth.mp3',
    'audio/20-synthmaster.mp3',
    'audio/21-decent-sampler.mp3',
    'audio/21-dm10.mp3',
    'audio/21-synthmaster.mp3',
    'audio/24-decent-sampler.mp3',
    'audio/24-dm10.mp3',
    'audio/24-j6-synth.mp3',
    'audio/24-wave-cloud.mp3',
    'audio/25-battlestation.mp3',
    'audio/25-decent-sampler.mp3',
    'audio/25-j6-synth.mp3',
    'audio/25-ruismaker-noir.mp3',
    'audio/25-synthmaster.mp3',
    'audio/26-animoog.mp3',
    'audio/26-decent-sampler.mp3',
    'audio/26-dm10.mp3',
    'audio/26-jsynth.mp3',
    'audio/26-reverie.mp3',
    'audio/27-decent-sampler.mp3',
    'audio/27-j6synth.mp3',
    'audio/27-reverie-choral.mp3',
    'audio/27-reverie-frozen-time.mp3',
    'audio/27-ruismaker-noir.mp3',
    'audio/27-synthmaster.mp3',
];
